<?php

//Allow the user to enter the verify email code that was generated as either part of the process, of if the user requested it.
//If code matches the code in the database, then it is marked as complete
session_start();


require_once("connectDB.php");


$code = $code_err = $retrivedCode = "";

//Determine source from the GET request
//Only happpen on first call to the page
//Where source exists, store in $_SESSION
//This is to generate a different message for the user, based on their source

if(isset($_GET["source"])){

    $_SESSION["src"] = $_GET["source"];
}
$source = $_SESSION["src"];


//POST request when the submit is pressed
//Get the code input by the user
//Access db to get code
//validate code

if($_SERVER["REQUEST_METHOD"] == "POST"){
 
    // Validate if a code is input

    $inp_code = trim($_POST["inputCode"]);

    if(empty($inp_code)){
        $code_err = "Please enter the code.";     
    } else {
        $code = $inp_code;
    }

    // Get any codes with 'current' status from the userCodes table for the user ID
    // There will only be one value because the create code routine sets any current records to 'expired' as part of code generation process

    $sql = "SELECT code FROM userCodes WHERE userID = ? AND status = ?";
    $stmt = $link->stmt_init();
        
    if($stmt->prepare($sql)){
        
        $stmt->bind_param("is", $param_id, $param_status);

        $param_id = $_SESSION["id"];
        $param_status = 'verifyemail';
            
        if($stmt->execute()){

            $stmt->store_result();
           
            if($stmt->num_rows() == 1){

                $stmt->bind_result($db_retCode);
                while($stmt->fetch()){
                    $retrievedCode = $db_retCode;
                    if ($retrievedCode != $code) {
                        $code_err = "Sorry, that code does not match the one that was sent..";
                        
                    }
                } 
            } else {
                echo "Something went wrong";  // No Data Returned
            }
        }

    } else{
                echo "Oops! Something went wrong. Please try again later.";
    }

    $stmt->close();

    if(empty($code_err)){

        // Code is correct. Update the database to set the code to status 'complete' so doesn't get picked up anymore

        $sql = "UPDATE userCodes SET status = ? WHERE userID = ?";
        $stmt = $link->stmt_init();
        
        if($stmt->prepare($sql)){
            
            $stmt->bind_param("si", $param_status, $param_id);
            
            $param_status = "complete";
            $param_id = $_SESSION["id"];
            
            
            if($stmt->execute()){

            } else{
                echo "Oops! Something went wrong. Please try again later.";
            }

            
        }

        
        $stmt->close();

        //As code is correct, the email is verified, so update the users table to do this

        $sql = "UPDATE users SET emailVerify = 'Y' WHERE id = ?";
        $stmt = $link->stmt_init();

        if($stmt->prepare($sql)){
            $stmt->bind_param("i", $param_id);

            $param_id = $_SESSION["id"];

            if($stmt->execute()){
                //Once complete, redirect the user to the page which they were on when they requested this.

                if (!empty($_SERVER['HTTPS']) && ('on' == $_SERVER['HTTPS'])) {
                    $uri = 'https://';
                } else {
                    $uri = 'http://';
                }
                $uri .= $_SERVER['HTTP_HOST'];
                
                if ($source == 'register') {
                   header('Location: '.$uri.'/login/dashboard.php');
                } else {
                   header('Location: '.$uri.'/login/journeyIndex.php');
                }

            } else{
                echo "Oops! Something went wrong. Please try again later.";
            }


            $stmt->close();
            }
        }
    $link->close();

}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Verify Email</title>
    <link rel="stylesheet" href="../css/siteStyle.css">
</head>
<body>
    <div>
        <h2>Enter Code</h2>
        <!-- Show a slightly different message to user if the code was generated by clicking verify my email (register) or trying to add a new journey (journeyrequest) -->
        <?php 
            if ($source == "register") {
                echo "<p>A Code has been sent to your registered email. Please check it and enter the code. If you cannot find it, check your junk folder:</p>";
            }
            else {
                echo "<p>A Code has been sent to your registered email. Without a registered email, we cannot be confident that we can send you notifications and therefore cannot allow new journeys to be input. If the email is incorrect, return to the dashboard and edit your email, the verify it. Please check your and enter the code. If you cannot find it, check your junk folder:</p>";
            }
            
        ?>
        <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post"> 
            <div>
                <label>Enter Code</label>
                <input type="input" name="inputCode" value="<?php echo $inp_code; ?>">
                <span><?php echo $code_err; ?></span>
            </div>
            <div>
                <input type="submit" value="Submit">
            </div>
        </form>
    </div>    
</body>
</html>
